### ISSUE TITLE
Output file name incompatibility between Python and R

### ISSUE THREAD

**Issue by stineb** [khufkens/gee_subset#1]
Following the example R script `R_query_plot.R`, the Python script `gee_subset.py` writes data into a file, named `<directory>/site_gee_subset.csv`. However, Python adds a string for the product name, `T1` in this case, from `os.path.basename(args.product)` (see l.208 in `gee_subset.py`). Thus, R doesn't find the respective file. This is resolved by the following (`R_query_plot.R`, l. 54):
```R
df = read.table( paste0( directory, "site_", tail( unlist( strsplit( product, "[/]" ) ), n=1 ), "_gee_subset.csv" ), sep = ",", header = TRUE )
```

**Comment by khufkens** [comment]
Thanks for the fix.

I updated the script to include a product name, this allows successive queries in the same directory (which at time limits juggling files), but broke the script. Didn't check.
