### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by KarlmerABC** [khufkens/gee_subset#10]
![image](https://user-images.githubusercontent.com/54607354/129809545-7fc269e0-b230-423f-8e7e-f61d4d27707c.png)

Great library. I have used it recently on Colab. I tried to run it today but this error appears.

**Comment by khufkens** [comment]
The package is written for python 2.6 or 2.7. Google colab probably uses python 3.x, which is stricter in terms of indentation. Feel free to fix the indentation of the code and do a pull request. However, I've little time to fix this right now myself. Alternatively create a colab session running python 2.7.

**Comment by KarlmerABC** [comment]
Thanks, @khufkens.
