### ISSUE TITLE
Invalid Geometry

### ISSUE THREAD

**Issue by mgmanalili** [khufkens/gee_subset#2]
Hi @khufkens,

I was trying to import gee_subset as a module but for some reason, ee has problem resolving the geometry part (when it reads the area as a region not as a point). 

The snippet is:

`import ee, gee_subset, sys
ee.Initialize()

df = gee_subset.gee_subset(product = "LANDSAT/LC08/C01/T1",
                           bands = "B4 B5",
                           start_date = "2015-01-01",
                           end_date = "2016-12-31",
                           latitude = 44.0646,
                           longitude = -71.2875,
                           scale = 0,
                           pad = 0)
`
It returns this error:
`---------------------------------------------------------------------------
EEException                               Traceback (most recent call last)
<ipython-input-228-05b64d4cae58> in <module>()
      6                            longitude = -71.2875,
      7                            scale = 0,
----> 8                            pad = 0)

/home/hilagavm/gee_subset/gee_subset/gee_subset.pyc in gee_subset(product, bands, start_date, end_date, latitude, longitude, scale, pad)
    130 
    131    # region values as generated by getRegion
--> 132    region = col.getRegion(geometry, int(scale)).getInfo()
    133 
    134    # stuff the values in a dataframe for convenience

/home/hilagavm/.local/lib/python2.7/site-packages/earthengine_api-0.1.144-py2.7.egg/ee/computedobject.pyc in getInfo(self)
     93       The object can evaluate to anything.
     94     """
---> 95     return data.getValue({'json': self.serialize()})
     96 
     97   def encode(self, encoder):

/home/hilagavm/.local/lib/python2.7/site-packages/earthengine_api-0.1.144-py2.7.egg/ee/data.pyc in getValue(params)
    267   """
    268   params['json_format'] = 'v2'
--> 269   return send_('/value', params)
    270 
    271 

/home/hilagavm/.local/lib/python2.7/site-packages/earthengine_api-0.1.144-py2.7.egg/ee/data.pyc in send_(path, params, opt_method, opt_raw)
    826       raise ee_exception.EEException('Invalid JSON: %s' % content)
    827     if 'error' in json_content:
--> 828       raise ee_exception.EEException(json_content['error']['message'])
    829     if 'data' not in content:
    830       raise ee_exception.EEException('Malformed response: ' + str(content))

EEException: ImageCollection.getRegion: Error in map(ID=LC08_001004_20150511):
Image.select: Pattern 'B' did not match any bands.`

**Comment by khufkens** [comment]
If using it as a python module you need to specify the parameters in the appropriate format (which is taken care of by the argument parser in the CLI implementation). In short, if it works on CLI it should work as a module and your parameters (formatting / formats) should be checked.

Also, the scale value can not be 0! The scale value determines the resolution of the output format, which defaults to the maximum product resolution if scale < true resolution. However, since this refers to a spatial resolution this can not be 0 as this does not make sense, physically, as it should always be > 0.

This works:
```python
#!/usr/bin/env python

import ee
import gee_subset
import sys
ee.Initialize()

df = gee_subset.gee_subset(product = "LANDSAT/LC08/C01/T1",
bands = ['B1', 'B2'],
start_date = '2015-01-01',
end_date = '2016-12-31',
latitude = 44.0646,
longitude = -71.2875,
scale = 1,
pad = 0)
```

**Comment by mgmanalili** [comment]
This worked. Thanks @khufkens !
