### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'long' objects

### ISSUE THREAD

**Issue by wiesehahn** [khufkens/gee_subset#6]
While I still cannot run the example in Winsows from R due to authentication error (credentials file is not found although when running the script directly in python it is found) I tried to run the script directly in python.

if using a csv-file for -f (site, latitude longitude) I got an error:

```pythonTraceback (most recent call last):
  File "C:/Users/user/Documents/google_earth_engine_subsets/gee_subset/gee_subset.py", line 255, in <module>
    print("processing: " + loc[1] + " at " + "%s / %s" % (loc[3],loc[2]))
TypeError: cannot concatenate 'str' and 'long' objects
```

My sites are numeric (1,2,3,... ).

Changing this line in the gee_subset.py script to 

```python # some feedback
      print("processing: " + str(loc[1]) + " at " + "%s / %s" % (loc[3],loc[2]))
```
and also he following 
```python
       # depending on output options write to file
       # or just print to console   
        if args.directory and not args.image:
          df.to_csv(args.directory + "/" + str(loc[1]) + "_" + os.path.basename(args.product) + "_gee_subset.csv", index = False)
        else:
          print(df)

```
helped for me.

**Comment by khufkens** [comment]
Could you do a pull request on this fix?

**Comment by khufkens** [comment]
Fixed here:
https://github.com/khufkens/gee_subset/commit/22f73c1d101f86a33fe6d62af1724ff4b29f7e95
