### ISSUE TITLE
Generating too many values for Landsat 8

### ISSUE THREAD

**Issue by kkgadiraju** [khufkens/gee_subset#7]
Hello,

I am using the following command: 

`./gee_subset.py -p "LANDSAT/LC08/C01/T1" -s 2013-01-01 -e 2018-12-31 -b "B4" "B5" -l 38.17619870263358 -91.7266592510949 `

to generate a time series, of B4 and B5 for Landsat 8, but I noticed that it is generating ~ 400 values, with the first 111 values between 2013-2018, and the next 100 or so values for different dates between 2013-2018. Is this expected behavior? I do not think so many values should be generated for a single location in the given time range, given the temporal frequency of Landsat 8. 

Appreciate your help.

**Comment by kkgadiraju** [comment]
Hello,

I am using the following command:

**Comment by kkgadiraju** [comment]
I think I figured it out. When there are overlapping tiles for the same location, information from all tiles is returned. Might be a good idea not to drop the 'id' column, and allow users to filter by row and column if needed.

**Comment by khufkens** [comment]
I removed dropping the `id` as it indeed obfuscates things in this sidelap scenario. This now should return the id properly and allow you to differentiate between the sources (tiles) queried.

Thanks for highlighting this, clearly didn't hit this scenario myself.
